May 15th
tlandryIntact/climate-resilience-dwg pull request #1
Opened 2023-05-15 21:07 UTC by tlandryIntact

Component section, first pass

2023-05-15 23:10 UTC, jongad requested changes

2023-05-15 23:10 UTC, jongad commented on 2023-07_Pilot-ER/sections/04-03-dri.adoc
> +IFC's participation to this pilot was conducted by the Centre for Climate and Geospatial Analytics (CCGA), a team of experts operating at Intact Data Lab. The main focus of this participation is to b
Is the IFC abbreviation detailed previously?

2023-05-15 23:10 UTC, jongad commented on 2023-07_Pilot-ER/sections/04-03-dri.adoc
> +IFC's participation to this pilot was conducted by the Centre for Climate and Geospatial Analytics (CCGA), a team of experts operating at Intact Data Lab. The main focus of this participation is to b
We use "outside world" a lot internally, but perhaps we want to use something different here.

2023-05-15 23:10 UTC, jongad commented on 2023-07_Pilot-ER/sections/04-03-dri.adoc
> +With close to 500 data, AI, machine learning and pricing experts, the Intact Data Lab has deployed almost 300 AI models in production to-date, helping transform outperformance advantage. It is focuse
```suggestion
With close to 500 experts in data, AI, machine learning and pricing, the Intact Data Lab has deployed almost 300 AI models in production to-date, helping transform outperformance advantage. It is focused on improving risk selection and making operations as efficient as possible while creating outstanding interactions 
```

2023-05-15 23:10 UTC, jongad commented on 2023-07_Pilot-ER/sections/04-03-dri.adoc
> +With close to 500 data, AI, machine learning and pricing experts, the Intact Data Lab has deployed almost 300 AI models in production to-date, helping transform outperformance advantage. It is focuse
Not sure what you mean by "helping transform outperformance advantage".

2023-05-15 23:10 UTC, jongad commented on 2023-07_Pilot-ER/sections/04-03-dri.adoc
> +with customers. Within Intact’s Data Lab, the Centre for Climate and Geospatial Analytics (CCGA) uses weather, climate, and geospatial data along with machine learning models to develop risk maps and
```suggestion
with customers. Within Intact’s Data Lab, the Centre for Climate and Geospatial Analytics (CCGA) uses weather, climate, and geospatial data along with machine learning models and claims data to develop risk maps and other specialized products to the business.
```

2023-05-15 23:10 UTC, jongad commented on 2023-07_Pilot-ER/sections/04-03-dri.adoc
> + * Identify current usages of wildfire risk maps at Intact by interviewing various business units;
```suggestion
 * Identify current usages of wildfire maps at Intact by interviewing various business units;
```

2023-05-15 23:10 UTC, jongad commented on 2023-07_Pilot-ER/sections/04-03-dri.adoc
> +To develop its component, Intact migrated its previous proprietary wildfire hazard model to a new private on-premise data science environment. For all key inputs to the model, external connections to
```suggestion
To develop its component, Intact migrated its previous proprietary wildfire hazard model to a new private on-premise data science environment. For all key inputs to the model, external connections to several open data repositories were established. To facilitate these access tests, several public open source datasets, such as climate model outputs, Earth observations, weather and geospatial, were vetted by the appropriate cybersecurity boards. The tests informed experts of changes in platforms offerings, of new data products specifications and of current authoritative scientific references. The following datasets were accessed specifically to produce an updated wildfire hazard map (GeoTiff), and to compute regional risk indicator by postal codes (CSV):
```

2023-05-15 23:10 UTC, jongad commented on 2023-07_Pilot-ER/sections/04-03-dri.adoc
> +In parallel, CCGA polled IFC's stakeholders about current and potential uses of wildfire risk products within their operations. This information was used to identify use cases supporting this pilot p
The term "multi-hazard" seems to suggest that we're developing a combined wildfire/flood model.

2023-05-15 23:10 UTC, jongad commented on 2023-07_Pilot-ER/sections/07-lessons_learned.adoc
> +- Definition of common documentation guidelines for terms and licences of endpoints would facilitate approval in cybersecurity-heavy environments. Individual security reviews for each participants an
```suggestion
- Definition of common documentation guidelines for terms and licences of endpoints would facilitate approval in cybersecurity-heavy environments. Individual security reviews for each participants and their endpoints is a tedious process. Having common terms as defined in OGC's master agreement, alongside applicable open source licences, would facilitate endpoint whitelisting.
```

2023-05-16 13:49 UTC, tlandryIntact commented on 2023-07_Pilot-ER/sections/04-03-dri.adoc
> +IFC's participation to this pilot was conducted by the Centre for Climate and Geospatial Analytics (CCGA), a team of experts operating at Intact Data Lab. The main focus of this participation is to b
Good catch, but here I think it's fine to use the expression "externally". Always easier to memorize to explain.

2023-05-16 13:51 UTC, tlandryIntact commented on 2023-07_Pilot-ER/sections/04-03-dri.adoc
> +With close to 500 data, AI, machine learning and pricing experts, the Intact Data Lab has deployed almost 300 AI models in production to-date, helping transform outperformance advantage. It is focuse
Corporate lingo taken straight from annual report. I might just cut the sentence.

2023-05-16 14:46 UTC, tlandryIntact commented on 2023-07_Pilot-ER/sections/04-03-dri.adoc
> +IFC's participation to this pilot was conducted by the Centre for Climate and Geospatial Analytics (CCGA), a team of experts operating at Intact Data Lab. The main focus of this participation is to b
Applied change

2023-05-16 14:51 UTC, tlandryIntact commented on 2023-07_Pilot-ER/sections/04-03-dri.adoc
> +In parallel, CCGA polled IFC's stakeholders about current and potential uses of wildfire risk products within their operations. This information was used to identify use cases supporting this pilot p
Adjusted wording

2023-05-16 14:51 UTC, tlandryIntact commented
Merging first PR to fork

2023-05-16 14:51 UTC, merged